---
title: "Human Analysis"
output: html_notebook
---

Read csv
```{r, echo=false}

# read data and initialize new storage format
df = read.csv(file.choose(), stringsAsFactors = FALSE)

```

Assemble the first and last points of pial sulci from the human_tracings.csv
```{r}

landmarks = data.frame(
  species = character(),
  specimen = numeric(),
  time = character(),
  sulcus = character(),
  hemisphere = character(),
  id = numeric(),
  x = numeric(),
  y = numeric(),
  z = numeric()
)


# handle which surface (white or gray)
surface = readline(prompt="Chose gray matter (pi) or white matter (wh)")
if(surface == 'pi') {
  sulci = list('ar', 'cb', 'ce', 'hr', 'if', 'ip', 'it', 'la', 'of', 'pc', 'po', 'pt', 'sf', 'st')  #pial sulci
} else if(surface == 'wh') {
  sulci = list('ar', 'ca', 'ce', 'ci', 'co', 'hr', 'if', 'ip', 'it', 'la', 'of', 'pc', 'po', 'pt', 'sf', 'st') #white sulci
} else {
  print("choose wh or pi")
  stop()
}



df = df[df$gm_or_wm == surface, ]


#isolate only first and last points for every sulcus
for (subject in unique(df$subject)) {
  for (time in unique(df[df$subject == subject, 'time'])) {
    for (hemi in list('lh', 'rh')) {
      for (sulcus in sulci) {
        temp = df[(df$sulcus == sulcus & df$subject == subject & df$hemisphere == hemi & df$time == time),
                c('species', 'subject', 'time', 'sulcus', 'hemisphere', 'index_number', 'x', 'y','z')]
        
        if (nrow(temp) == 0) {
          cat(subject, sulcus, 'does not exist')
          break
        }
      
        max = temp[temp$index_number == max(temp$index_number),]
        max$index_number = 2
  
        min = temp[temp$index_number == min(temp$index_number),]
        min$index_number = 1
  
        landmarks = rbind(landmarks, max, min)
      }
      
      
    }
    
    if(surface == 'pi') {
      for (sulcus in list('pl', 'ol', 'fl')) {
           temp = df[(df$sulcus == sulcus & df$subject == subject & df$time == time),
                  c('species', 'subject', 'time', 'sulcus', 'hemisphere', 'index_number', 'x', 'y','z')]
  
          max = temp[temp$index_number == max(temp$index_number),]
          max$index_number = 2
  
          min = temp[temp$index_number == min(temp$index_number),]
          min$index_number = 1
  
          landmarks = rbind(landmarks, max, min)
      }
    }
  }
}
```

Format file for TPS
```{r}
# format file for create.tps

landmarks$specimen = paste(landmarks$subject, landmarks$time, sep='_')

landmarks = landmarks[, c('species', 'specimen','time', 'sulcus', 'hemisphere','x', 'y', 'z')]

# exclude 14 20 months bc of is missing
landmarks = subset(landmarks, specimen != '14_20months')


#should be 62 for first and last point of human pial sulci, 64 for white matter sulci
num = as.integer(readline(prompt = 'How many landmarks are there?'))

for (i in 1:nrow(landmarks)) {
  if ((i - 1) %% num != 0) {
    landmarks$species[i] = ''
    landmarks$specimen[i] = ''
    landmarks$time[i] = ''
  }
}


write.csv(landmarks, file = "human_landmarks.csv")

```

Create TPS
```{r}
library('borealis')

# make tps
create.tps(input.file = "human_landmarks.csv",
           output.file = "human_landmarks.tps",
           id.factors = c("species"),
           separator = "_",
           include.scale = FALSE)

```

Read TPS + Procrustes Alignment
```{r, echo=FALSE}
library('geomorph')

data = readland.tps("human_landmarks.tps", specID = "ID", negNA = FALSE, readcurves = FALSE, warnmsg = TRUE)

gpa_aligned = gpagen(data, curves = NULL, surfaces = NULL, PrinAxes = TRUE,
 max.iter = NULL, ProcD = TRUE, Proj = TRUE, print.progress = FALSE)

# Summarize data
summary(gpa_aligned)
plotAllSpecimens(gpa_aligned$coords,mean=TRUE)

```

PCA and Classifiers
```{r, echo=FALSE}
ids = landmarks[landmarks$specimen != '', 'specimen']
months = landmarks[landmarks$specimen != '', 'time']

years = c()
# get age in years (grouped)
for (value in months) {
  split = unlist(strsplit(value, 'm'))
  num = unlist(strsplit(split[1], 'w'))
  
  
  if(as.integer(num[1]) < 24) {
    year = '<2'
  } else if (as.integer(num[1]) < 48) {
    year = '2 to 4'
  } else if (as.integer(num[1]) < 72) {
    year = '4 to 6'
  } else if(as.integer(num[1]) < 96) {
    year = '6 to 8'
  } else if (as.integer(num[1]) >= 96) {
    year = '8+'
  }
  
  years = c(years, year)
}

# export classifiers for morphoj
classifiers = data.frame(paste(ids,'human', sep='_'), years)
write.csv(classifiers, 'human_classifiers.csv')

#add factors to R analysis
gpa_aligned$time = as.factor(months)
gpa_aligned$years_old = as.factor(years)

# PCA summary
PCA = gm.prcomp(gpa_aligned$coords)
plot(PCA, col=gpa_aligned$time, main="PCA, colored by age at scan")

plot(PCA, col=gpa_aligned$years_old, main='PCA')
legend('topright', fill=unique(gpa_aligned$years_old), legend=unique(gpa_aligned$years_old))

summary(PCA)


```

Scree Plot
```{r, echo=FALSE}

#Scree plot
scree_data = data.frame(
  Component = 1:length(PCA$sdev),
  Variance = PCA$sdev^2 / sum(PCA$sdev^2)
)

library(ggplot2)
ggplot(scree_data, aes(x = Component, y = Variance)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  xlab("Principal Components") +
  ylab("Proportion of Variance Explained") +
  theme_minimal()

```

Potential correlations (PCs, size, shape, age)
```{r}

#get pc scores
library(Morpho) 

RW<-relWarps(data, scale = TRUE, CSinit = TRUE, alpha = 0, 
 orp = TRUE, noalign = FALSE)


#look for correlation to centroid size for first 2 principle components (others contribute very small (<10%) amount to overall shape variation
pc1<-RW$bescores[,1]  #for PC1
print(cor.test(pc1,gpa_aligned$Csize)) 

pc2<-RW$bescores[,2] #for PC2
print(cor.test(pc2,gpa_aligned$Csize))


#effects of age group and centroid size on shape
gdf <- geomorph.data.frame(gpa_aligned, years=gpa_aligned$years_old)
fit = procD.lm(gpa_aligned$coords~gpa_aligned$years_old+log(gpa_aligned$Csize), data=gdf)
anova(fit)


#look for interaction between age group and allometry
modelInteraction<-procD.lm(gpa_aligned$coords~gpa_aligned$years_old*log(gpa_aligned$Csize), data = gdf)
anova(modelInteraction)


plotAllometry(fit, size=gdf$Csize, logsz=TRUE, method='RegScore', col=gdf$years)
legend('bottomright', fill=unique(gdf$years), legend=unique(gdf$years))

```