---
title: "Human and Macaque Combined"
output: html_notebook
---

```{r}
# get csv files
human = read.csv(file.choose(), stringsAsFactors = FALSE)
macaque = read.csv(file.choose(), stringsAsFactors = FALSE)
```


Assemble combined csv for resampling (not necessary for 2 point analysis)
```{r}
df1 = macaque
df2 = human[, c('species', 'subject', 'time', 'hemisphere', 'gm_or_wm', 'sulcus', 'index_number', 'x', 'y', 'z')]

combined = rbind(df1, df2)

# sulci categories (pial and white)
human_sulc = list('ar','hr', 'if', 'it', 'pc', 'pt', 'sf')
macaque_sulc = list('arc', 'pr','lu', 'di', 'io')
combined_sulc = list('ca', 'ce', 'ci', 'co','la', 'st', 'po', 'of', 'ip', 'cb')

# assign categories 
combined$present_in = 'both'

for (sulcus in human_sulc) {
  combined$present_in[combined$sulcus == sulcus] = 'human'
}

for (sulcus in macaque_sulc) {
  combined$present_in[combined$sulcus == sulcus] = 'macaque'
}

write.csv(combined, 'combined_tracings.csv')
```

Assemble combined csv for 2 point analysis
```{r}
landmarks = data.frame(
  species = character(),
  specimen = numeric(),
  time = character(),
  sulcus = character(),
  hemisphere = character(),
  id = numeric(),
  x = numeric(),
  y = numeric(),
  z = numeric()
)

# handle which surface (white or gray)
surface = readline(prompt="Chose gray matter (pi) or white matter (wh)")
if(surface == 'pi') {
  sulci = list('ce', 'la', 'st', 'po', 'of', 'ip', 'cb')  #pial sulci
} else if(surface == 'wh') {
  sulci = list('ca', 'ce', 'ci', 'co','ip', 'la', 'of', 'po', 'st') #white sulci
} else {
  print("choose wh or pi")
  stop()
}

# choose surface to investigate
human = human[human$gm_or_wm == surface,]
macaque = macaque[macaque$gm_or_wm == surface,]

df = rbind(macaque, human[, c('species', 'subject', 'time', 'hemisphere', 'gm_or_wm', 'sulcus', 'index_number', 'x', 'y', 'z')])


landmarks = data.frame(
  species = character(),
  specimen = numeric(),
  time = character(),
  sulcus = character(),
  hemisphere = character(),
  id = numeric(),
  x = numeric(),
  y = numeric(),
  z = numeric()
)

for (species in c('macaque', 'human')) {
  for (subject in unique(df[df$species == species, 'subject'])) {
    for (time in unique(df[df$species == species & df$subject == subject, 'time'])) {
      for (hemi in list('lh', 'rh')) {
        for (sulcus in sulci) {
          temp = df[(df$sulcus == sulcus & df$subject == subject & df$species == species & df$hemisphere == hemi & df$time == time),
                  c('species', 'subject', 'time', 'sulcus', 'hemisphere', 'index_number', 'x', 'y','z')]
          
          if (nrow(temp) == 0) {
          cat(subject, sulcus, 'does not exist')
          break
        }
        
          max = temp[temp$index_number == max(temp$index_number),]
          max$index_number = 2
    
          min = temp[temp$index_number == min(temp$index_number),]
          min$index_number = 1
    
          landmarks = rbind(landmarks, max, min)
        }
      }
      
      if (surface == 'pi') {
        for (sulcus in list('pl', 'ol', 'fl')) {
             temp = df[(df$sulcus == sulcus & df$subject == subject & df$species == species & df$time == time),
                    c('species', 'subject', 'time', 'sulcus', 'hemisphere', 'index_number', 'x', 'y','z')]
    
            max = temp[temp$index_number == max(temp$index_number),]
            max$index_number = 2
    
            min = temp[temp$index_number == min(temp$index_number),]
            min$index_number = 1
    
            landmarks = rbind(landmarks, max, min)
        }
      }
    }
  }
}


```

Handle outliers 
```{r}
#remove outlier 25_1month and problem 14_20months
landmarks = subset(landmarks, specimen != '25_1month')
landmarks = subset(landmarks, specimen != '14_20months')

landmarks$specimen = paste(landmarks$specimen, landmarks$species, sep='_')

# #remove outliers as defined by plotOutliers (for pial sulci, white had no outliers)
# 
# outliers = list('23_80months_human', '14_11months_human', '13_7months_human', '15_13months_human', '1_10months_human', '17_8months_human', '2_8months_human', '19_75months_human', '10_9months_human', '3_8months_human', '4_12months_human', '12_13months_human', '18_92months_human', '5_11months_human', '11_6months_human', '24_87months_human', '8_12months_human', '25_89months_human', '9_7months_human', '7_8months_human', '16_92months_human', '6_7months_human', '19_9months_human')

for (outlier in outliers) {
  landmarks = subset(landmarks, landmarks$specimen != outlier)
}
```

Format File for TPS
```{r}

# format file for create.tps
landmarks = landmarks[order(landmarks$subject, landmarks$time, landmarks$species),]
landmarks$specimen = paste(landmarks$subject, landmarks$time, sep='_')
landmarks = landmarks[, c('species', 'specimen','time', 'sulcus', 'x', 'y', 'z')]


#should be 34 for first and last point of macaque + human pial sulci, 36 for white
num = as.integer(readline(prompt = 'How many landmarks are there?'))

for (i in 1:nrow(landmarks)) {
  if ((i - 1) %% num != 0) {
    landmarks$species[i] = ''
    landmarks$specimen[i] = ''
    landmarks$time[i] = ''
  }
}


write.csv(landmarks, file = "combined_landmarks.csv")

```


Create TPS
```{r}
library('borealis')

# make tps
create.tps(input.file = "combined_landmarks.csv",
           output.file = "combined_landmarks.tps",
           include.scale = FALSE)

```


Read TPS + Procrustes Alignment
```{r, echo=FALSE}
library('geomorph')

data = readland.tps("combined_landmarks.tps", specID = "ID", negNA = FALSE, readcurves = FALSE, warnmsg = TRUE)

gpa_aligned = gpagen(data, curves = NULL, surfaces = NULL, PrinAxes = TRUE,
 max.iter = NULL, ProcD = TRUE, Proj = TRUE, print.progress = FALSE)

# Summarize data
summary(gpa_aligned)
plotAllSpecimens(gpa_aligned$coords,mean=TRUE)

```

PCA and Classifiers
```{r, echo=FALSE}
ids = landmarks[landmarks$specimen != '', 'specimen']
months = landmarks[landmarks$specimen != '', 'time']
species = landmarks[landmarks$species != '', 'species']

#add factors to R analysis
gpa_aligned$species = as.factor(species)

classifiers = data.frame(paste(ids, species, sep='_'), species)  
write.csv(classifiers, 'combined_classifiers.csv')

# PCA summary
PCA = gm.prcomp(gpa_aligned$coords)
#plot(PCA, col=gpa_aligned$time, main="PCA, colored by age at scan")

plot(PCA, col=gpa_aligned$species, main='PCA')
legend('topright', fill=unique(gpa_aligned$species), legend=unique(gpa_aligned$species))

plotOutliers(gpa_aligned$coords, inspect.outliers = FALSE)

summary(PCA)

```

Scree Plot
```{r, echo=FALSE}

#Scree plot
scree_data = data.frame(
  Component = 1:length(PCA$sdev),
  Variance = PCA$sdev^2 / sum(PCA$sdev^2)
)

library(ggplot2)
ggplot(scree_data, aes(x = Component, y = Variance)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  xlab("Principal Components") +
  ylab("Proportion of Variance Explained") +
  theme_minimal()

```

Potential correlations (PCs, size, shape, age)
```{r}
#get pc scores
library(Morpho) 

RW<-relWarps(data, scale = TRUE, CSinit = TRUE, alpha = 0, 
 orp = TRUE, noalign = FALSE)


#look for correlation to centroid size for first 2 principle components (others contribute very small (<10%) amount to overall shape variation
pc1<-RW$bescores[,1]  #for PC1
print(cor.test(pc1,gpa_aligned$Csize)) 

pc2<-RW$bescores[,2] #for PC2
print(cor.test(pc2,gpa_aligned$Csize))


#effects of species and centroid size on shape
gdf <- geomorph.data.frame(gpa_aligned, species=gpa_aligned$species)
fit = procD.lm(gpa_aligned$coords~gpa_aligned$species+log(gpa_aligned$Csize), data=gdf)
anova(fit)


#look for interaction between species and allometry
modelInteraction<-procD.lm(gpa_aligned$coords~gpa_aligned$species*log(gpa_aligned$Csize), data = gdf)
anova(modelInteraction)


plotAllometry(fit, size=gdf$Csize, logsz=TRUE, method='RegScore', col=gdf$species)
legend('topright', fill=unique(gpa_aligned$species), legend=unique(gpa_aligned$species))

```
