---
title: "Combined Resampling Morphometrics"
output: html_notebook
---

Read csv
```{r}
df = read.csv('combined_tracings.csv')
```


Resample curves
```{r}

library('Morpho')
library('geomorph')

resampled = data.frame(
  x = numeric(),
  y = numeric(),
  z = numeric(),
  species = character(),
  subject = character(),
  surface = character(),
  time = character(),
  sulcus = character(),
  hemisphere = character()
)

# handle which surface (white or gray)
surface = readline(prompt="Chose gray matter (pi) or white matter (wh)")
if(surface == 'pi') {
  sulci = list('ce', 'la', 'st', 'po', 'of', 'ip', 'cb')  #pial sulci
} else if(surface == 'wh') {
  sulci = list('ca', 'ce', 'ci', 'co','ip', 'la', 'of', 'po', 'st') #white sulci
} else {
  print("choose wh or pi")
  stop()
}

# choose surface to investigate
df = df[df$gm_or_wm == surface,]

#resampling function
resample = function(sulcus, subject, species, hemi, time, df) {
  temp = df[(df$sulcus == sulcus & df$subject == subject & df$species == species & df$hemisphere == hemi & df$time == time), c('x', 'y','z')]
          
  # exclude empty sulci
  if (nrow(temp) == 0) {
   stop(paste(subject, time, sulcus, 'DNE', sep=' '))
  }
          
  # resample curve
  temp = data.frame(resampleCurve(temp, n=150))
  curve = cbind(temp$X1, temp$X2, temp$X3)
  
  # get starting point
  start = curve[1,]
  
  temp = data.frame(digit.curves(start, curve, 98, closed = FALSE)) #98 semi landmarks = start + end
  
  # reintroduce metadata
  temp$species = species
  temp$subject = subject
  temp$hemisphere = hemi
  temp$time = time
  temp$surface = surface
  temp$sulcus = sulcus
  
  return(temp)
}

for (species in list('macaque', 'human')) {
  for (subject in unique(df[df$species == species, 'subject'])) {
    for (time in unique(df[df$species == species & df$subject == subject, 'time'])) {
      for (hemi in list('lh', 'rh')) {
        for (sulcus in sulci) {
          tryCatch({resampled = rbind(resample(sulcus, subject, species, hemi, time, df), resampled)},
                   error = function(e) {
                     cat(conditionMessage(e), '\n')
                   })
        }
      }
      
      if (surface == 'pi') {
        for (sulcus in list('pl', 'ol', 'fl')) {
         tryCatch({resampled = rbind(resample(sulcus, subject, species, 'central', time, df), resampled)},
                   error = function(e) {
                     cat(conditionMessage(e), '\n')
                   })
        }
      }
    }
  }
}

# renamed resampled points
colnames(resampled)[colnames(resampled) == "X1"] ="x"
colnames(resampled)[colnames(resampled) == "X2"] ="y"
colnames(resampled)[colnames(resampled) == "X3"] ="z"

```
Handle outliers 
```{r}
#remove outlier 25_1month and problem 14_20months

filtered_df = resampled

filtered_df$specimen = paste(filtered_df$subject, filtered_df$time, filtered_df$species, sep='_')

filtered_df = subset(filtered_df, specimen != '25_1month_macaque')
filtered_df = subset(filtered_df, specimen != '14_20months_human')

#remove outliers as defined by plotOutliers 

outliers = list()

for (outlier in outliers) {
  filtered_df = subset(filtered_df, filtered_df$specimen != outlier)
}

```

Select sulcus
```{r}
# will analyze one sulcus at a time
sulcus = readline(prompt="Select sulcus to investigate. It must be present in both humans and macaques.")
filtered_df  = filtered_df[filtered_df$sulcus == sulcus,]

```

Select hemisphere
```{r}
# will analyze one hemisphere at a time
hemisphere = readline(prompt="Select hemisphere to investigate: lh, rh, or central.")
filtered_df  = filtered_df[filtered_df$hemisphere == hemisphere,]

```

Format Data
```{r}
filtered_df = filtered_df[order(filtered_df$subject, filtered_df$time, filtered_df$species, filtered_df$sulcus),]

```

Procrustes Alignment
```{r}

#should be 200 points for one sulcus, 1700 for all pial sulci 1800 for all white sulci
num = as.integer(readline(prompt = 'How many landmarks are there?'))

#format array
data = arrayspecs(cbind(filtered_df$x, filtered_df$y, filtered_df$z), num, 3)

# add specimen ids
ids = c()
species = c()

for(i in seq(1, nrow(filtered_df), by = num)) {
  ids = c(ids, filtered_df[i, 'specimen'])
  species = c(species, filtered_df[i, 'species'])
}

dimnames(data) = list(
  Landmark = 1:num ,  # names for landmarks
  Dimension = c("X", "Y", "Z"),       # names for dimensions
  Specimen = ids      # names for specimens
)

#handle semilandmarks (num = number of landmarks)
numSemi = num - (2 * num / 100)
semiLm = c()
slideStart = c() # previous lm
slideEnd = c()  # next lm

# there is a "real" lm at the start and end of every 100 pt curve
for (i in 1:num) {
  if (i %% 100 != 0 & i %% 100 != 1) {
    semiLm = c(semiLm, i)
    slideStart = c(slideStart, i - 1)
    slideEnd = c(slideEnd, i + 1)
  }
}

sliders <- cbind(slideStart, semiLm, slideEnd)

gpa_aligned = gpagen(data, curves = sliders, surfaces = NULL, PrinAxes = TRUE,
 max.iter = NULL, ProcD = TRUE, Proj = TRUE, print.progress = FALSE)
```

Procrustes Results
```{r}
# Summarize data
summary(gpa_aligned)
plotOutliers(gpa_aligned$coords, inspect.outliers = FALSE)
plot3d(gpa_aligned$consensus)
```


Additional Procustes Plot
```{r}
plotAllSpecimens(gpa_aligned$coords)

```

PCA and Classifiers
```{r, echo=FALSE}

#add factors to R analysis
gpa_aligned$species = as.factor(species)
gpa_aligned$ids = ids

# PCA summary
PCA = gm.prcomp(gpa_aligned$coords)

plot(PCA, col=gpa_aligned$species, main='PCA')
legend('topright', fill=unique(gpa_aligned$species), legend=unique(gpa_aligned$species))

plot(PCA, col=gpa_aligned$species, main='PCA', axis1=2, axis2 =3)
legend('topright', fill=unique(gpa_aligned$species), legend=unique(gpa_aligned$species))

plot(PCA, col=gpa_aligned$species, main='PCA', axis1=3, axis2 =4)
legend('topright', fill=unique(gpa_aligned$species), legend=unique(gpa_aligned$species))


summary(PCA)

```

Scree Plot
```{r, echo=FALSE}

#Scree plot
scree_data = data.frame(
  Component = 1:length(PCA$sdev),
  Variance = PCA$sdev^2 / sum(PCA$sdev^2)
)

library(ggplot2)
ggplot(scree_data, aes(x = Component, y = Variance)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  xlab("Principal Components") +
  ylab("Proportion of Variance Explained") +
  theme_minimal()

```

Potential correlations (PCs, size, shape, age)
```{r}
#get pc scores
library(Morpho) 

RW<-relWarps(data, scale = TRUE, CSinit = TRUE, alpha = 0, 
 orp = TRUE, noalign = FALSE)


#look for correlation to centroid size
pc1<-RW$bescores[,1]  #for PC1
print(cor.test(pc1,gpa_aligned$Csize)) 

pc2<-RW$bescores[,2] #for PC2
print(cor.test(pc2,gpa_aligned$Csize))

pc3<-RW$bescores[,3] #for PC2
print(cor.test(pc3,gpa_aligned$Csize))

pc4<-RW$bescores[,4] #for PC2
print(cor.test(pc4,gpa_aligned$Csize))


#effects of species and centroid size on shape
gdf <- geomorph.data.frame(gpa_aligned, species=gpa_aligned$species)
fit = procD.lm(gpa_aligned$coords~gpa_aligned$species+log(gpa_aligned$Csize), data=gdf)
anova(fit)


#look for interaction between species and allometry
modelInteraction<-procD.lm(gpa_aligned$coords~gpa_aligned$species*log(gpa_aligned$Csize), data = gdf)
anova(modelInteraction)


plotAllometry(fit, size=gdf$Csize, logsz=TRUE, method='RegScore', col=gdf$species)
legend('topleft', fill=unique(gpa_aligned$species), legend=unique(gpa_aligned$species))

```
